Add tower custom buildconfig
redhat-cop/containers-quickstarts pull request #492
Opened 2021-04-15 21:28 UTC by paulbarfuss

#### What is this PR About?
This quickstart gives an example of how to deploy a custom Ansible Tower image with custom virtualenvs and RPMs directly to your Openshift internal image registry to be consumed by the Ansible Tower 3.8 installer.

#### How do we test this?
Following the steps in the README will yield a buildconfig and an imagestream in your Openshift cluster. Run the applier, and validate:

```bash
$ oc get buildconfig tower-ocp -n tower-ocp
$ oc get imagestream tower-ocp -n tower-ocp
```

cc: @redhat-cop/day-in-the-life

2021-04-30 15:20 UTC, garethahealy requested changes
can you add a test to conftes.sh similar to:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/_test/conftest.sh#L23-L32

the key bit, is:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/_test/conftest.sh#L24

which points at the yaml resources (i.e.: your template)

2021-06-23 15:18 UTC, paulbarfuss commented
Thanks @garethahealy that was very straightforward and looks to be passign with an `ok` now.

2021-06-23 17:03 UTC, oybed approved these changes
LGTM

2021-06-23 17:03 UTC, oybed commented
/lgtm

2021-07-04 07:05 UTC, garethahealy commented
/approve
/lgtm

2021-07-04 07:05 UTC, garethahealy approved these changes

2021-07-04 07:05 UTC, merged